---
# SPDX-FileCopyrightText: 2022 Ethel Morgan
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.14.0
    hooks:
      - id: reuse
        fail_fast: true

  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        language: system
        entry: nixfmt
        types: [nix]
        fail_fast: true

      - id: nix-flake-check
        name: nix flake check
        language: system
        entry: nix flake check
        pass_filenames: false
